---
language: python

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' > ansible.cfg

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/

