---

- name: Importing key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: New Repository
  shell: echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

- name: Instalando via apt
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "apt-transport-https"
    - "sublime-text"